### PR TITLE
Attachments target octet-stream content type

### PR DESCRIPTION
**Pull request by nathancolgate**
Currently the `parseHTML` function for attachments only uses a `figure[data-trix-attachment]` selector. This makes sense as the Rhino editor is heavily geared towards Trix attachments being images.

However, while implementing the [tiptap mention extension](https://tiptap.dev/api/nodes/mention), we ran into a challenge where we want to capture/deliver mentions as Action Text Attachments.

Due to the broad selector above, we had to disable the attachments extension altogether to stop the editor from trying to turn our `@mentions` into image attachments.

```javascript
rhinoEditor.starterKitOptions = {
    ...rhinoEditor.starterKitOptions,
    rhinoGallery: false,
    rhinoAttachment: false,
    rhinoFigcaption: false,
    rhinoImage: false,
  }
```

This PR targets the `octet-stream` content type specifically, which is what Rails delivers by default.

Merging this PR would allow users to keep the image attachment functionality of Rhino, while also adding custom content types for other attachments/extensions via the `attachable_content_type` method on objects. For example:

```ruby
class User < ApplicationRecord
  def attachable_content_type
    "application/vnd.rails.user"
  end
end

### CODE REVIEW

**Comment by KonnorRogers** [comment]
Hmmm....I'm not sure overriding the MimeType is the right way to go here.

I'm not 100%, but I think this would break anyone using the old "CustomAttachment" functionality from Trix.

however, perhaps we do something slightly different.

would something like using `data-rhino-serialize="false"` perhaps be a better way to get around this issue?

the other option is to do something like: `<div content=" "></div>` and make it a blank string with a space.

`content` use the old escape hatch that Trix used to prevent turning attachments into images and what's used in Rhino as well

https://github.com/KonnorRogers/rhino-editor/blob/a942226bcb9351a3a502a534f2e7a8e84ffc443d/src/exports/extensions/attachment.ts#L330

**Comment by nathancolgate** [comment]
🤷 I'm not sure either, but for us it was the easiest way to differentiate different kinds of attachments.

* `content` - we didn't want to sniff around here and create some kind of dependency between the view and the javascript powering the editor (the designers just want to modify the views and not worry about something breaking)
* `sgid` - i'm not sure if the trix JS can parse things. I know rails can reverse engineer what object type it is. This might be cool.
* `contentType` - low hanging fruit. 

Check out how we're doing mention support over in #113 . It might shed some light on where we're coming from, and how we're trying to handle all kinds of "attachments".

Thanks again for your work on this! It's been a fun week exploring.

**Comment by KonnorRogers** [comment]
@nathancolgate 

1.) honestly, I agree. TipTap having an editable schema renders the `content` attribute an ugly hack that exists purely for backwards compatibility.

2.) right now SGID is purely an attribute we need to send back to Rails. Rhino doesn't do any introspection.

3.) fair point. IIRC contentType may actually be HTML for custom attachments so this may be okay...

**Comment by nathancolgate** [comment]
@KonnorRogers Even after changing the `attachable_content_type` override? Hmmm... that's not what we're seeing.

**Comment by KonnorRogers** [comment]
@nathancolgate Changing the `attachable_content_type` works. But for a new application with no changes is what I meant.

**Pull request merged**
